print("-"*60)
print("-"*60)
print()
print("Welcome to addition Program".center(60))
print()
x =int(input("Enter x :"))
y = int(input("Enter y :"))
print()
print("x = {x}".center(60))
print("y = {y}".center(60))
print("{x} + {y}  = {x+y}".center(60))
print("Thanks for using addition Program")
print()
print("y = {y}")
print("-"*60)
print("-"*60)
